package com.bdefender.test.Guariglia;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.MenuButton;

public class launchMenuController {
	@FXML
	private Button startPlayBtn;
	@FXML
	private Button tutorialBtn;
	@FXML
	private MenuButton mapSelectionBtn;
	@FXML
	private Label titleLable;

	// Event Listener on Button[#startPlayBtn].onAction
	@FXML
	public void play(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#tutorialBtn].onAction
	@FXML
	public void tutorialPopup(ActionEvent event) {
		// TODO Autogenerated
	}
}
